import { useEffect, useState, type ReactNode } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import {
  ArrowLeft, ArrowRight, BarChart3, Bell, BriefcaseBusiness, Camera, Check,
  CheckCircle2, ChevronRight, CircleUserRound, Clock3, Eye, FileText, Home,
  LayoutGrid, LockKeyhole, Mic, Pause, Play, Plus, Search, Send, Settings,
  ShieldCheck, Sparkles, Star, Upload, UserRound, UsersRound, Video, X,
} from 'lucide-react'
import './app.css'
import './design-system.css'

type Role = 'talent' | 'company'
type Profile = { id: string; score: number; area: string; city: string; skills: string[]; evidence: string; metrics: number[] }

const profiles: Profile[] = [
  { id: '01', score: 94, area: 'Automação industrial', city: 'Recife, PE', skills: ['CLP Siemens', 'Diagnóstico', 'NR-10'], evidence: 'Localizou a falha de intertravamento e validou o circuito antes da energização.', metrics: [96, 94, 88, 92] },
  { id: '02', score: 89, area: 'Eletrotécnica', city: 'Campinas, SP', skills: ['Comandos elétricos', 'Diagramas', 'Sensores'], evidence: 'Executou medições com método e comunicou cada hipótese com clareza.', metrics: [90, 96, 92, 84] },
  { id: '03', score: 84, area: 'Manutenção industrial', city: 'Curitiba, PR', skills: ['Manutenção', 'Inversores', 'Preventiva'], evidence: 'Propôs uma solução pragmática para reduzir paradas e facilitar manutenção.', metrics: [86, 91, 81, 90] },
  { id: '04', score: 78, area: 'Sistemas industriais', city: 'Fortaleza, CE', skills: ['IoT', 'Sensores', 'Dados'], evidence: 'Sugeriu monitoramento adicional e alertas preditivos para a linha.', metrics: [80, 84, 94, 76] },
]

const talentNav = [[Home, 'Visão geral', '/talento'], [Video, 'Demonstrações', '/talento/gravar'], [CircleUserRound, 'Perfil técnico', '/talento/perfil'], [BriefcaseBusiness, 'Oportunidades', '/talento/oportunidades']] as const
const companyNav = [[Home, 'Visão geral', '/empresa'], [Search, 'Buscas', '/empresa/nova-busca'], [LayoutGrid, 'WHO Board', '/empresa/board'], [BarChart3, 'Pipeline', '/empresa/pipeline']] as const

function Logo() { return <Link className="brand" to="/"><span>W</span><b>WHO</b></Link> }
function Button({ children, variant = 'primary', onClick, disabled, type = 'button' }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'danger' | 'quiet'; onClick?: () => void; disabled?: boolean; type?: 'button' | 'submit' }) {
  return <button className={`button ${variant}`} type={type} onClick={onClick} disabled={disabled}>{children}</button>
}
function Tag({ children, muted = false }: { children: ReactNode; muted?: boolean }) { return <span className={`tag ${muted ? 'muted' : ''}`}>{children}</span> }

function PublicNav() {
  return <header className="public-nav"><Logo/><nav><a href="#produto">Produto</a><a href="#processo">Como funciona</a><Link to="/entrar">Entrar</Link><Link className="nav-cta" to="/cadastro">Criar conta</Link></nav></header>
}

function Landing() {
  return <div className="landing"><PublicNav/><main>
    <section className="landing-hero">
      <div className="landing-copy"><Tag>Seleção por evidências</Tag><h1>Competência real.<br/><span>Sem achismo.</span></h1><p>A WHO transforma demonstrações técnicas em decisões de contratação claras, comparáveis e livres de vieses de identidade.</p><div className="landing-actions"><Link className="button primary" to="/cadastro?role=talent">Quero demonstrar meu trabalho <ArrowRight/></Link><Link className="button secondary" to="/cadastro?role=company">Quero encontrar talentos</Link></div><small><ShieldCheck/> A identidade permanece protegida até a empresa avaliar as evidências.</small></div>
      <div className="product-preview" id="produto"><div className="preview-head"><div><small>DEMANDA ATIVA</small><b>Diagnóstico de CLP</b></div><span>4 evidências</span></div><div className="preview-context"><Sparkles/><p>A IA identificou <b>3 critérios críticos</b>: lógica de intertravamento, comandos elétricos e segurança NR-10.</p></div>{profiles.slice(0, 3).map((p, i) => <div className="preview-row" key={p.id}><span>{i + 1}</span><div><b>Perfil {p.id}</b><small>{p.skills.slice(0, 2).join(' · ')}</small></div><strong>{p.score}%</strong></div>)}</div>
    </section>
    <section className="process" id="processo"><div className="section-intro"><span>COMO FUNCIONA</span><h2>Uma decisão melhor começa com uma evidência melhor.</h2></div><div className="process-grid">{[
      ['01', 'Conte o problema', 'A empresa descreve a situação em voz ou texto, sem preencher uma vaga tradicional.'],
      ['02', 'Mostre o trabalho', 'O talento grava uma tarefa real e explica as decisões tomadas durante a execução.'],
      ['03', 'Compare evidências', 'A IA organiza sinais técnicos e recomenda perfis sem revelar dados pessoais.'],
    ].map(([n, t, d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  </main><footer><Logo/><p>Talento demonstrado. Decisão explicável.</p><small>© 2026 WHO</small></footer></div>
}

function Auth({ signup = false }: { signup?: boolean }) {
  const navigate = useNavigate(); const [role, setRole] = useState<Role>('talent')
  return <div className="auth-layout"><aside><Logo/><div><Tag>WHO PLATFORM</Tag><h1>{signup ? 'Comece pelo que você sabe fazer.' : 'Continue de onde parou.'}</h1><p>Uma experiência de contratação baseada em trabalho real, não em palavras-chave.</p></div><small>Privacidade e evidência desde o primeiro passo.</small></aside><form onSubmit={(e) => { e.preventDefault(); navigate(role === 'talent' ? '/talento' : '/empresa') }}><Link className="back-link" to="/"><ArrowLeft/> Voltar</Link><h2>{signup ? 'Criar conta' : 'Entrar'}</h2><p>{signup ? 'Escolha como você quer usar a WHO.' : 'Use a conta de demonstração para explorar.'}</p>{signup && <div className="role-picker"><button type="button" className={role === 'talent' ? 'selected' : ''} onClick={() => setRole('talent')}><UserRound/><span><b>Sou talento</b><small>Quero demonstrar competências</small></span></button><button type="button" className={role === 'company' ? 'selected' : ''} onClick={() => setRole('company')}><BriefcaseBusiness/><span><b>Sou empresa</b><small>Quero resolver um problema</small></span></button></div>}{signup && <label>Nome completo<input required placeholder="Seu nome"/></label>}<label>E-mail<input required type="email" defaultValue={signup ? '' : 'demo@who.com.br'} placeholder="voce@email.com"/></label><label>Senha<input required type="password" defaultValue={signup ? '' : '12345678'} placeholder="Mínimo de 8 caracteres"/></label><Button type="submit">{signup ? 'Criar conta' : 'Entrar'} <ArrowRight/></Button><small className="auth-switch">{signup ? 'Já possui uma conta?' : 'Ainda não possui conta?'} <Link to={signup ? '/entrar' : '/cadastro'}>{signup ? 'Entrar' : 'Cadastre-se'}</Link></small></form></div>
}

function AppShell({ role, title, subtitle, action, children }: { role: Role; title: string; subtitle: string; action?: ReactNode; children: ReactNode }) {
  const nav = role === 'talent' ? talentNav : companyNav
  return <div className="app-shell">
    <aside aria-label="Navegação principal">
      <Logo/>
      <div className="account"><div>{role === 'talent' ? 'MS' : 'AA'}</div><span><b>{role === 'talent' ? 'Marina Silva' : 'Atlas Automação'}</b><small>{role === 'talent' ? 'Talento' : 'Empresa'}</small></span></div>
      <nav>{nav.map(([Icon, label, to]) => <NavLink end key={to} to={to} title={label}><Icon/>{label}</NavLink>)}</nav>
      <div className="sidebar-bottom"><button type="button"><Settings/>Configurações</button><Link to="/"><ArrowLeft/>Sair da demonstração</Link></div>
    </aside>
    <section className="workspace">
      <header><div><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{action}<button aria-label="Notificações"><Bell/></button><span aria-label={role === 'talent' ? 'Marina Silva' : 'Atlas Automação'}>{role === 'talent' ? 'MS' : 'AA'}</span></div></header>
      <main>{children}</main>
    </section>
  </div>
}

function Metric({ value, label, detail }: { value: string; label: string; detail?: string }) { return <div className="metric"><strong>{value}</strong><span>{label}</span>{detail && <small>{detail}</small>}</div> }

function TalentDashboard() {
  const navigate = useNavigate()
  return <AppShell role="talent" title="Olá, Marina" subtitle="Seu perfil está ativo e recebendo novas evidências."><section className="hero-panel talent"><div><Tag>PERFIL 82% COMPLETO</Tag><h2>Mostre mais uma habilidade.</h2><p>Grave uma tarefa real. A WHO transforma seu processo em evidências técnicas que empresas conseguem avaliar.</p><Button onClick={() => navigate('/talento/gravar')}><Camera/> Gravar demonstração</Button></div><div className="progress-number"><strong>82</strong><span>%</span><small>perfil completo</small></div></section><section className="metrics-strip"><Metric value="128" label="Visualizações" detail="+18 esta semana"/><Metric value="3" label="Matches ativos"/><Metric value="2" label="Novos convites"/></section><div className="content-grid"><section className="surface"><div className="surface-head"><div><small>PRÓXIMO PASSO</small><h3>Fortaleça seu perfil técnico</h3></div><Link to="/talento/perfil">Ver perfil <ChevronRight/></Link></div><div className="profile-summary"><div className="profile-avatar">MS</div><div><b>Marina Silva</b><p>Automação industrial · IFS Aracaju</p><div className="tag-list"><Tag>CLP Siemens</Tag><Tag>Diagnóstico</Tag><Tag>NR-10</Tag></div></div></div><div className="profile-progress"><span><b>6 de 8</b> competências validadas</span><i><em/></i></div></section><section className="surface activity-surface"><div className="surface-head"><div><small>ATIVIDADE</small><h3>O que aconteceu</h3></div></div>{[['Seu perfil foi publicado', 'Hoje, 10:42'], ['24 pessoas viram sua demonstração', 'Ontem'], ['Atlas Automação enviou um convite', '08 jul']].map(([t, d]) => <div className="activity-item" key={t}><CheckCircle2/><span><b>{t}</b><small>{d}</small></span></div>)}</section></div></AppShell>
}

function Recorder() {
  const navigate = useNavigate(); const [state, setState] = useState<'ready' | 'recording' | 'paused' | 'done'>('ready'); const [seconds, setSeconds] = useState(0)
  useEffect(() => { if (state !== 'recording') return; const timer = window.setInterval(() => setSeconds((v) => v + 1), 1000); return () => clearInterval(timer) }, [state])
  const time = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
  return <AppShell role="talent" title="Nova demonstração" subtitle="Explique o que está fazendo enquanto executa a tarefa."><div className="stepper"><span className="done"><Check/>Preparar</span><span className="active">2 Gravar</span><span>3 Revisar</span><span>4 Publicar</span></div><section className="record-layout"><div className="record-stage"><span className={`record-status ${state}`}>{state === 'recording' ? 'GRAVANDO' : state === 'paused' ? 'PAUSADO' : state === 'done' ? 'CONCLUÍDO' : 'CÂMERA PRONTA'}</span><UserRound/><strong>{time}</strong></div><aside><small>ANTES DE COMEÇAR</small><h3>Deixe visível</h3><ul><li><Check/>A tarefa e o equipamento</li><li><Check/>As ferramentas utilizadas</li><li><Check/>Os cuidados de segurança</li></ul><div className="record-controls">{state === 'ready' && <Button onClick={() => setState('recording')}><Play/> Iniciar gravação</Button>}{state === 'recording' && <><Button variant="secondary" onClick={() => setState('paused')}><Pause/> Pausar</Button><Button variant="danger" onClick={() => setState('done')}>Finalizar</Button></>}{state === 'paused' && <Button onClick={() => setState('recording')}><Play/> Continuar</Button>}{state === 'done' && <><Button variant="secondary" onClick={() => { setState('ready'); setSeconds(0) }}>Regravar</Button><Button onClick={() => navigate('/talento/processando')}>Analisar vídeo <ArrowRight/></Button></>}</div><button className="upload-link"><Upload/> Enviar um arquivo</button></aside></section></AppShell>
}

function Processing({ role = 'talent' }: { role?: Role }) {
  const navigate = useNavigate(); const [step, setStep] = useState(0)
  const items = role === 'talent' ? ['Enviando vídeo', 'Transcrevendo explicação', 'Identificando competências', 'Verificando evidências', 'Montando perfil'] : ['Interpretando a demanda', 'Extraindo critérios técnicos', 'Buscando demonstrações', 'Ordenando evidências', 'Preparando o WHO Board']
  useEffect(() => { const timer = window.setInterval(() => setStep((v) => { if (v >= items.length - 1) { clearInterval(timer); window.setTimeout(() => navigate(role === 'talent' ? '/talento/perfil' : '/empresa/board'), 600); return v } return v + 1 }), 600); return () => clearInterval(timer) }, [items.length, navigate, role])
  return <AppShell role={role} title={role === 'talent' ? 'Analisando demonstração' : 'Construindo o WHO Board'} subtitle="Você pode acompanhar o que a IA está fazendo."><section className="processing-card" aria-live="polite" aria-busy="true"><div className="processing-icon"><Sparkles/></div><small>ANÁLISE EM ANDAMENTO</small><h2>{role === 'talent' ? 'Transformando trabalho em evidência' : 'Encontrando experiências relevantes'}</h2><p>Nenhuma decisão será tomada automaticamente. A IA apenas organiza os sinais para sua revisão.</p><div className="processing-list">{items.map((item, index) => <div className={index < step ? 'complete' : index === step ? 'current' : ''} key={item}>{index < step ? <Check/> : <span>{index + 1}</span>}<b>{item}</b>{index === step && <i/>}</div>)}</div></section></AppShell>
}

function TalentProfile() {
  return <AppShell role="talent" title="Perfil técnico" subtitle="Uma visão baseada no que você demonstrou."><section className="profile-header surface"><div className="profile-avatar large">MS</div><div><Tag>PERFIL VERIFICADO</Tag><h2>Marina Silva</h2><p>Automação industrial · Aracaju, SE</p></div><Button variant="secondary">Editar perfil</Button></section><div className="content-grid profile-content"><section className="surface"><small>RESUMO TÉCNICO</small><h3>Diagnóstico e automação industrial</h3><p>Atuação demonstrada em investigação de falhas, programação de CLPs e manutenção segura de sistemas industriais.</p><h4>Competências validadas</h4><div className="tag-list"><Tag>Programação de CLP</Tag><Tag>Comandos elétricos</Tag><Tag>Diagnóstico</Tag><Tag>NR-10</Tag></div><h4>Demonstração mais recente</h4><div className="video-row"><span><Play/></span><div><b>Diagnóstico de motores comandados por CLP</b><small>04:32 · 6 evidências identificadas</small></div><ChevronRight/></div></section><aside className="surface"><small>DISPONIBILIDADE</small><div className="availability"><CheckCircle2/><span><b>Disponível</b><small>Integral · Presencial ou híbrido</small></span></div><h4>Ferramentas</h4><p>TIA Portal, multímetro, CLP S7-1200</p><h4>Segurança</h4><p>NR-10, bloqueio e etiquetagem, verificação de ausência de tensão.</p></aside></div></AppShell>
}

function Opportunities() {
  return <AppShell role="talent" title="Oportunidades" subtitle="Convites relacionados às evidências do seu perfil."><div className="tabs"><button className="active">Todos <span>3</span></button><button>Novos <span>2</span></button><button>Em conversa <span>1</span></button></div><section className="opportunity-list">{[['Atlas Automação', 'Técnico de Automação', 94], ['Nortech Sistemas', 'Analista de Manutenção', 88]].map(([company, job, score]) => <article key={company as string}><div className="company-avatar">{String(company)[0]}</div><div><Tag>NOVO CONVITE</Tag><h3>{job}</h3><p>{company} · Presencial · Recife, PE</p><div className="tag-list"><Tag muted>CLP</Tag><Tag muted>Diagnóstico</Tag><Tag muted>NR-10</Tag></div></div><div className="opportunity-score"><strong>{score}%</strong><small>aderência</small><Button variant="secondary">Ver convite</Button></div></article>)}</section></AppShell>
}

function CompanyDashboard() {
  const navigate = useNavigate()
  return <AppShell role="company" title="Visão geral" subtitle="Transforme uma necessidade operacional em critérios claros."><section className="hero-panel company"><div><Tag>NOVA BUSCA</Tag><h2>Qual problema precisa ser resolvido?</h2><p>Conte a situação do seu jeito. A WHO organiza o contexto e encontra profissionais que já demonstraram saber resolver algo semelhante.</p><Button onClick={() => navigate('/empresa/nova-busca')}><Plus/> Descrever uma demanda</Button></div><Mic/></section><section className="metrics-strip"><Metric value="4" label="Buscas ativas"/><Metric value="18" label="Evidências encontradas" detail="+5 esta semana"/><Metric value="6" label="Convites enviados"/></section><div className="content-grid"><section className="surface"><div className="surface-head"><div><small>BUSCAS RECENTES</small><h3>Demandas em andamento</h3></div></div>{[['Diagnóstico e configuração de CLP', '4 perfis prontos para revisão'], ['Manutenção em inversores', '8 perfis em análise']].map(([title, status], i) => <div className="search-row" key={title}><span>{i + 1}</span><div><b>{title}</b><small>{status}</small></div><Tag>{i === 0 ? 'REVISAR' : 'ANALISANDO'}</Tag></div>)}</section><aside className="surface next-actions"><small>PRÓXIMAS AÇÕES</small><h3>Continue de onde parou</h3><button onClick={() => navigate('/empresa/board')}><UsersRound/><span><b>Revisar 4 novos matches</b><small>WHO Board atualizado hoje</small></span><ChevronRight/></button><button onClick={() => navigate('/empresa/pipeline')}><Clock3/><span><b>Acompanhar 2 convites</b><small>Aguardando resposta</small></span><ChevronRight/></button></aside></div></AppShell>
}

function NewDemand() {
  const navigate = useNavigate(); const [mode, setMode] = useState<'input' | 'review' | 'questions'>('input'); const [text, setText] = useState('Minha linha está parando porque três motores não estão sendo acionados corretamente pelo mesmo CLP. Preciso diagnosticar a ligação e configurar o sistema.')
  return <AppShell role="company" title="Nova busca" subtitle="Descreva o problema como explicaria para alguém da sua equipe."><div className="stepper"><span className={mode === 'input' ? 'active' : 'done'}>1 Contexto</span><span className={mode === 'review' ? 'active' : mode === 'questions' ? 'done' : ''}>2 Interpretação</span><span className={mode === 'questions' ? 'active' : ''}>3 Detalhes</span><span>4 Confirmar</span></div><section className="demand-card"><div className="assistant-message"><Sparkles/><div><b>Assistente WHO</b><p>{mode === 'input' ? 'O que está acontecendo na operação?' : mode === 'review' ? 'Revise a interpretação antes de continuar.' : 'Só preciso de três detalhes para melhorar a busca.'}</p></div></div>{mode === 'input' && <><div className="input-modes"><button><Mic/><span><b>Gravar áudio</b><small>Fale livremente</small></span></button><button className="selected"><FileText/><span><b>Escrever</b><small>Use suas próprias palavras</small></span></button></div><label>Descrição da situação<textarea value={text} onChange={(e) => setText(e.target.value)}/></label><Button onClick={() => setMode('review')}>Continuar <ArrowRight/></Button></>}{mode === 'review' && <><div className="transcript-box"><small>TRANSCRIÇÃO</small><textarea value={text} onChange={(e) => setText(e.target.value)}/></div><div className="ai-interpretation"><Sparkles/><div><small>INTERPRETAÇÃO DA IA</small><p>Falha no acionamento simultâneo de três motores controlados por um CLP. A busca deve priorizar experiência em lógica de intertravamento, comandos elétricos e diagnóstico seguro.</p><div className="tag-list"><Tag>Automação</Tag><Tag>CLP</Tag><Tag>NR-10</Tag></div></div></div><Button onClick={() => setMode('questions')}>A interpretação está correta <ArrowRight/></Button></>}{mode === 'questions' && <><div className="questions">{[['Modelo do CLP', 'Siemens S7-1200'], ['Janela para manutenção', 'Até 2 horas'], ['Prazo para solução', 'Próximas 48 horas']].map(([label, value]) => <label key={label}>{label}<select defaultValue={value}><option>{value}</option><option>Não sei informar</option></select></label>)}</div><Button onClick={() => navigate('/empresa/processando')}>Gerar WHO Board <Sparkles/></Button></>}</section></AppShell>
}

function Score({ value }: { value: number }) { return <div className="score" role="meter" aria-label={`${value}% de aderência`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><strong>{value}</strong><span>%</span><small>aderência</small></div> }

function Board() {
  const navigate = useNavigate(); const [selected, setSelected] = useState<string[]>([])
  const [filter, setFilter] = useState<'all' | 'high' | 'available'>('all')
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : current)
  const visibleProfiles = filter === 'high' ? profiles.filter((profile) => profile.score >= 90) : filter === 'available' ? profiles.slice(0, 3) : profiles
  return <AppShell role="company" title="WHO Board" subtitle="Uma recomendação explicada por evidências, não por currículo."><div className="board-layout"><aside className="board-context"><small>DEMANDA</small><h2>Diagnóstico e configuração de CLP</h2><p>Três motores não são acionados corretamente pelo mesmo controlador.</p><hr/><small>CRITÉRIOS CRÍTICOS</small><ul><li><Check/>Lógica de intertravamento</li><li><Check/>Comandos elétricos</li><li><Check/>Segurança NR-10</li></ul><div className="ai-note"><Sparkles/><p>A IA encontrou <b>4 demonstrações</b> com evidências diretamente relacionadas.</p></div></aside><section className="ranking"><div className="ranking-toolbar"><div><b>Perfis recomendados</b><span>Selecione 2 ou 3 perfis para comparar evidências</span></div><div role="group" aria-label="Filtrar perfis"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Todos</button><button className={filter === 'high' ? 'active' : ''} onClick={() => setFilter('high')}>90%+</button><button className={filter === 'available' ? 'active' : ''} onClick={() => setFilter('available')}>Disponível</button></div></div>{visibleProfiles.map((profile, index) => <article className={selected.includes(profile.id) ? 'selected' : ''} key={profile.id}><button className="select-profile" aria-label={`Selecionar perfil ${profile.id}`} aria-pressed={selected.includes(profile.id)} onClick={() => toggle(profile.id)}>{selected.includes(profile.id) && <Check/>}</button><span className="rank">0{index + 1}</span><div className="blind-identity"><LockKeyhole/><small>PERFIL {profile.id}</small></div><div className="profile-evidence"><div><Tag>{profile.area}</Tag><h3>Perfil {profile.id}</h3><p>{profile.city} · Identidade protegida</p></div><div className="tag-list">{profile.skills.map((skill) => <Tag muted key={skill}>{skill}</Tag>)}</div><blockquote>“{profile.evidence}”</blockquote><button onClick={() => navigate(`/empresa/match/${profile.id}`)}>Ver análise completa <ArrowRight/></button></div><Score value={profile.score}/></article>)}</section></div>{selected.length >= 2 && <div className="selection-bar"><span><b>{selected.length} selecionados</b><small>Escolha até 3 perfis</small></span><div>{selected.map((id) => <i key={id}>{id}</i>)}</div><Button onClick={() => navigate('/empresa/comparar')}>Comparar evidências <BarChart3/></Button></div>}</AppShell>
}

function Compare() {
  return <AppShell role="company" title="Comparação" subtitle="Compare os sinais mais relevantes para esta demanda."><Link className="back-link" to="/empresa/board"><ArrowLeft/> Voltar ao WHO Board</Link><section className="compare-table"><div className="compare-line heading"><b>Critério</b>{profiles.slice(0, 3).map((p) => <div key={p.id}><span className="locked"><LockKeyhole/></span><h3>Perfil {p.id}</h3><Tag>{p.score}% ADERÊNCIA</Tag></div>)}</div>{[['Capacidade técnica', 0], ['Segurança', 1], ['Comunicação', 2], ['Precisão', 3]].map(([label, index]) => <div className="compare-line" key={String(label)}><b>{label}</b>{profiles.slice(0, 3).map((p) => <div className="metric-bar" key={p.id}><strong>{p.metrics[Number(index)]}</strong><i><em style={{ width: `${p.metrics[Number(index)]}%` }}/></i></div>)}</div>)}<div className="compare-line evidence-line"><b>Evidência principal</b>{profiles.slice(0, 3).map((p) => <p key={p.id}>{p.evidence}</p>)}</div></section></AppShell>
}

function MatchDetail() {
  const { id = '01' } = useParams(); const profile = profiles.find((p) => p.id === id) ?? profiles[0]; const [revealed, setRevealed] = useState(false); const [invite, setInvite] = useState(false)
  return <AppShell role="company" title={revealed ? 'Marina Silva' : `Perfil ${profile.id}`} subtitle="Análise detalhada das evidências relacionadas à demanda."><div className="detail-actions"><Link className="back-link" to="/empresa/board"><ArrowLeft/> WHO Board</Link><div><Button variant="secondary"><Star/> Salvar</Button><Button onClick={() => setInvite(true)}><Send/> Convidar</Button></div></div><div className="match-grid"><section><div className="identity-card surface"><div className={revealed ? 'profile-avatar large' : 'locked-avatar'}>{revealed ? 'MS' : <LockKeyhole/>}</div><div><Tag>{revealed ? 'IDENTIDADE REVELADA' : 'IDENTIDADE PROTEGIDA'}</Tag><h2>{revealed ? 'Marina Silva' : `Perfil ${profile.id}`}</h2><p>{profile.area} · {profile.city}</p></div><Score value={profile.score}/></div><article className="surface rationale"><small>JUSTIFICATIVA DO MATCH</small><h3>Por que este perfil foi recomendado</h3><p>{profile.evidence} O método demonstrado é diretamente aplicável ao contexto descrito pela empresa.</p><div className="tag-list">{profile.skills.map((skill) => <Tag key={skill}><Check/>{skill}</Tag>)}</div></article><article className="surface"><div className="surface-head"><div><small>EVIDÊNCIA EM VÍDEO</small><h3>Trecho relacionado à demanda</h3></div><Tag>02:14 — 03:08</Tag></div><div className="video-evidence"><Play/></div><blockquote>“Primeiro verifico se os contatores recebem o sinal do CLP. Se o programa libera apenas um deles, preciso conferir a lógica de intertravamento antes da ligação.”</blockquote></article></section><aside className="surface indicators"><small>INDICADORES</small>{[['Técnica', profile.metrics[0]], ['Segurança', profile.metrics[1]], ['Comunicação', profile.metrics[2]], ['Precisão', profile.metrics[3]]].map(([label, value]) => <div className="indicator" key={String(label)}><span>{label}<b>{value}</b></span><i><em style={{ width: `${value}%` }}/></i></div>)}<hr/><small>PONTO DE ATENÇÃO</small><p>Validar adaptação ao modelo específico instalado na unidade.</p>{!revealed ? <Button variant="secondary" onClick={() => setRevealed(true)}><Eye/> Revelar identidade</Button> : <div className="revealed"><CheckCircle2/><span><b>Identidade revelada</b><small>A ação foi registrada.</small></span></div>}</aside></div>{invite && <div className="modal-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="invite-title"><button aria-label="Fechar convite" onClick={() => setInvite(false)}><X/></button><Send/><h2 id="invite-title">Convidar para entrevista</h2><p>O talento receberá o contexto da oportunidade e poderá responder ao convite.</p><label>Mensagem<textarea defaultValue="Olá! Analisamos suas evidências e gostaríamos de conversar sobre uma oportunidade na Atlas Automação."/></label><Button onClick={() => setInvite(false)}>Enviar convite</Button></div></div>}</AppShell>
}

function Pipeline() {
  const columns: Array<[string, string[]]> = [['Novos', ['Perfil 04']], ['Convidados', ['Perfil 01', 'Perfil 02']], ['Entrevista', ['Marina Silva']], ['Proposta', []]]
  return <AppShell role="company" title="Pipeline" subtitle="Acompanhe as conversas iniciadas a partir do WHO Board."><div className="pipeline-board">{columns.map(([title, items]) => <section key={String(title)}><header><b>{title}</b><span>{items.length}</span></header>{items.map((item, index) => <article key={item}><Tag>{index === 0 ? '94% MATCH' : '89% MATCH'}</Tag><h3>{item}</h3><p>Técnico de Automação</p><small><Clock3/> Atualizado hoje</small></article>)}{items.length === 0 && <div className="empty-column">Nenhum perfil nesta etapa</div>}</section>)}</div></AppShell>
}

function App() {
  return <BrowserRouter><Routes><Route path="/" element={<Landing/>}/><Route path="/entrar" element={<Auth/>}/><Route path="/cadastro" element={<Auth signup/>}/><Route path="/talento" element={<TalentDashboard/>}/><Route path="/talento/gravar" element={<Recorder/>}/><Route path="/talento/videos" element={<Recorder/>}/><Route path="/talento/processando" element={<Processing/>}/><Route path="/talento/perfil" element={<TalentProfile/>}/><Route path="/talento/oportunidades" element={<Opportunities/>}/><Route path="/empresa" element={<CompanyDashboard/>}/><Route path="/empresa/nova-busca" element={<NewDemand/>}/><Route path="/empresa/buscas" element={<NewDemand/>}/><Route path="/empresa/processando" element={<Processing role="company"/>}/><Route path="/empresa/board" element={<Board/>}/><Route path="/empresa/comparar" element={<Compare/>}/><Route path="/empresa/match/:id" element={<MatchDetail/>}/><Route path="/empresa/pipeline" element={<Pipeline/>}/><Route path="*" element={<Landing/>}/></Routes></BrowserRouter>
}

export default App
